export const initialLists = [
	{
		settings: {
			id: 1,
			title: "My Day",
			isMain: true,
			pinned: false,
			theme: null,
			icon: "assets/svgs/sun.svg",
		},
		tasks: [],
		completedTasks: [],
		importantTasks: [],
	},
	{
		settings: {
			id: 2,
			title: "All",
			isMain: true,
			pinned: false,
			theme: null,
			icon: "assets/svgs/all.svg",
		},
		tasks: [],
		completedTasks: [],
		importantTasks: [],
	},
	{
		settings: {
			id: 4,
			title: "Completed",
			isMain: true,
			pinned: false,
			theme: null,
			icon: "assets/svgs/checked.svg",
		},
		tasks: [],
		completedTasks: [],
		importantTasks: [],
	},
	{
		settings: {
			id: 5,
			title: "Planned",
			isMain: true,
			pinned: false,
			theme: null,
			icon: "assets/svgs/calendar.svg",
		},
		tasks: [],
		completedTasks: [],
		importantTasks: [],
	},
	{
		settings: {
			id: 6,
			title: "Tasks",
			isMain: true,
			pinned: false,
			theme: null,
			icon: "assets/svgs/list.svg",
		},
		tasks: [],
		completedTasks: [],
		importantTasks: [],
	},
];
export const initialSettings = {
	addToTop: true,
	confirmBeforeDeletion: true,
	light: false,
	showAll: true,
	showCompleted: true,
	showImportant: true,
	showPlanned: true,
	starToTop: true,
	playSound: true,
	theme: "blue",
};
